name: skyid
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - opencv
  - astropy
  - pip
  - pip:
      - requests
      - python-dotenv
      - Pillow
